### ISSUE TITLE
Map TODO

### ISSUE THREAD

**Issue by pewpewpy** [pewpewpy/Geotagger#2]
- [ ] Add play/pause
- [ ] Add date/time selection
- [ ] Figure out logic so track timeline is based on an accurate time scale
